# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 824760c7f107bd7456ff85054a2ed6a4e6b0c9a174ea96ca47d08c79a267a09d95e9d9659dc5cbb9f2c865bf52a96491551501addcbf8faf39078ae9ccdf1121

test:
  secret_key_base: 94303a8ca170990ed79a01ec6a79a69deb40fb8fc2fbdcf10fcaeacf79b3d5391f241eaba98608075c06969868e8cef482efa54eb3e8460f6eabe5e0795f1e39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
